### ISSUE TITLE
Doesn't handle actors who aren't found

### ISSUE THREAD

**Issue by eliasmalik** [FACG2/200#16]
If the actor API cannot find the actor, the code throws errors and the UI ends up like this:

<img width="714" alt="screen shot 2017-07-27 at 09 57 25" src="https://user-images.githubusercontent.com/12719553/28658030-20686338-72b2-11e7-8bac-c3c177bf2963.png">

**Comment by Walidmash** [comment]
Thanks @eliascodes  
This been mentioned in #15
